# Change these first
owner: prettybot # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Ikyu
    url: https://www.ikyu.com
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
